notifications:
  email: false

dist: bionic

language: c
compiler: gcc
cache: ccache

git:
  depth: 3

addons:
  apt:
    packages:
      - autopoint
      - docbook-simple
      - docbook-xsl
      - doxygen
      - gettext
      - gpgsm
      - graphviz
      - jimsh
      - libdb-dev
      - libgdbm-dev
      - libgnutls28-dev
      - libgpgme11-dev
      - libgss-dev
      - libidn2-0-dev
      - libkyotocabinet-dev
      - liblmdb-dev
      - liblua5.2-dev
      - liblz4-dev
      - libncursesw5-dev
      - libnotmuch-dev
      - libqdbm-dev
      - librocksdb-dev
      - libsasl2-dev
      - libssl-dev
      - libtdb-dev
      - libtokyocabinet-dev
      - libxml2-utils
      - libzstd-dev
      - lua5.2
      - luarocks
      - lynx
      - xsltproc

install:
  - luarocks install --local busted
  - git clone --depth 1 https://github.com/neomutt/neomutt-test-files.git ~/test-files

before_script:
  - ccache --zero-stats
  - export ANSI_CLEAR
  - export -f travis_fold
  - export -f travis_nanoseconds
  - export -f travis_time_finish
  - export -f travis_time_start
  # - eval $(luarocks path --bin)
  - export NEOMUTT_TEST_DIR="$HOME/test-files"
  - (cd ~/test-files && ./setup.sh)

script:
  - .travis/release-test.sh

after_script:
  - ccache --show-stats

