notifications:
  email: false

dist: bionic

language: c
compiler: gcc

addons:
  coverity_scan:
    project:
      name: "flatcap/neomutt"
      description: "test code"
    notification_email: rich@flatcap.org
    build_command: "make"
    branch_pattern: coverity

git:
  depth: 3

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt COVERITY_SCAN_TOKEN=XYZ" command using the project repo's public key
   - secure: "bOuRgszbB/kbDN8geXfzx9TTGlZ/Qx9NVeojvmi5Zj8M8rhlSAJrXCq+hkh7PnfTkEbpy4U28BQ85w+T1B7MiwzEMQheN2RcMojC0MZYsBYXVR/yTalob8abh/Y7I16IaMaorRR757YswvUbmQA6z2Fb5fmpxhuyYHSlViAD92/4i6yCg4tKHLfBJyph8I1dRh11WAJiRRnQ+ZBHRLML4ne/LMq/v3Hamf0PY/pOR0qivmK4taRSLIbnGC4N9TFEJtN0r1rYI4eBsjGuikVFdzbYj+mcnBfnfsE6lxeZSLaDmKNpzoenfujQBnjpWq086LCGXl1kSRYzvZUCH5Q/8BcIBUEAifwHWy8shUfsf85YNQbzMLBEBbEbsOUO6IJjX0EH+otPte/LIWzNsQSoWVtxsVPWxYLDttBwuJJt39RxjzlTT0JT+ETYghIN1KM44vpI7B1mUYv2i/o4CHzm2FzHfiK9s6W9T5iJp70S+pQyqAbw3AYLqsseKsJqFV+mw41AMXBhxW0QFQdBJCS6OqhavLAn03Odd73PXniYxNW3j6i7n5hqj1WdrXd9K00HRhenEqBfkMpI3vt6QjGFu5H+8T4NtxcVAp0V/lwXYv26qbbl6CWr9HMrTrq2AIImHfPqhf+gBSAzabjS1QHdrRwnvz1qNYI7pnXqLIijdqc="

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi

