.TH Config
.de EX
.BR Example:
.in +4n
.nf
.ft CW
..
.de EE
.ft R
.fi
.in -4n
..

.TP
.B inews
.nf
Type: command
Default: ""
.fi
.TS
box;
\fBExpando\fP \fBDescription\fP
.TP
%a .TP
account url
.TP
%p .TP
port
.TP
%P .TP
port if specified
.TP
%s .TP
news server name
.TP
%S .TP
url schema
.TP
%u .TP
username
.TE

